[project]
name = "ax-study"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jihyunkims495-sys", email = "jihyunkims495@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
ax-study = "ax_study:main"

[build-system]
requires = ["uv_build>=0.12.2,<0.13.0"]
build-backend = "uv_build"
